In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# 元素的形状和总数
x.shape,x.numel()

(torch.Size([12]), 12)

In [5]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.tensor([[1,2,2],[1,4,5],[4,5,6]])

tensor([[1, 2, 2],
        [1, 4, 5],
        [4, 5, 6]])

In [8]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y,x-y

(tensor([ 3.,  4.,  6., 10.]), tensor([-1.,  0.,  2.,  6.]))

In [9]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2,1,4,3],[2,4,5,6],[6,5,4,3]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 2.,  4.,  5.,  6.],
         [ 6.,  5.,  4.,  3.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  2.,  4.,  5.,  6.],
         [ 8.,  9., 10., 11.,  6.,  5.,  4.,  3.]]))

In [10]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
x.sum()

tensor(66.)

In [13]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [14]:
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [15]:
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])