In [2]:
import torch

A = torch.arange(20).reshape(5,4)
A


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [3]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [4]:
x = torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [5]:
a = torch.arange(20,dtype=float).reshape(5,4)
b = a.clone()

a,a+b

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]], dtype=torch.float64))

In [6]:
# 两个矩阵按元素乘法
a * b

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]], dtype=torch.float64)

In [7]:
a = 2
x = torch.arange(24).reshape(2,3,4)
a+x,(a*x).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [8]:
x.sum()

tensor(276)

In [11]:
a = torch.arange(24).reshape(2,3,4)
print(a)
a_sum_axis0 = a.sum(axis=0)
a_sum_axis0,a_sum_axis0.shape

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [14]:
a = torch.arange(24).reshape(2,3,4)
print(a)
a_sum_axis1 = a.sum(axis=1)
a_sum_axis1,a_sum_axis1.shape

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


(tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 torch.Size([2, 4]))

In [17]:
a = torch.arange(24).reshape(2,3,4)
a.mean(dtype=torch.float32),a.sum() / a.numel()

(tensor(11.5000), tensor(11.5000))

In [18]:
# 计算总和或均值时保持轴数不变
sum_a = a.sum(axis=1,keepdim=True)
sum_a

tensor([[[12, 15, 18, 21]],

        [[48, 51, 54, 57]]])

In [19]:
a / sum_a

tensor([[[0.0000, 0.0667, 0.1111, 0.1429],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6000, 0.5556, 0.5238]],

        [[0.2500, 0.2549, 0.2593, 0.2632],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.4167, 0.4118, 0.4074, 0.4035]]])

In [24]:
# 某个轴计算A元素的累积总和
print(a)
a.cumsum(axis=0)
a.shape,a.cumsum(axis=0).shape,a.cumsum(axis=0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


(torch.Size([2, 3, 4]),
 torch.Size([2, 3, 4]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 14, 16, 18],
          [20, 22, 24, 26],
          [28, 30, 32, 34]]]))

In [30]:
# 点积是相同位置的按元素乘积的和
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4,dtype=torch.float)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [31]:
# 可以通过执行按元素乘法，然后进行求和来表示两个向量的点积
torch.sum(x*y)

tensor(6.)

In [32]:
# 用于矩阵和向量相乘的函数
a = torch.arange(12).reshape(2,6)
b = torch.arange(6)
torch.mv(a,b)

tensor([ 55, 145])

In [34]:
# 两个矩阵想乘
# 定义两个矩阵
mat1 = torch.tensor([[1, 2],
                     [3, 4],
                     [5, 6]])
mat2 = torch.tensor([[7, 8],
                     [9, 10]])

# 进行矩阵乘法
result = torch.mm(mat1, mat2)
result

tensor([[ 25,  28],
        [ 57,  64],
        [ 89, 100]])

In [35]:
# L2范数是向量元素平方和的平方根
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [36]:
# L1范数，它表示为向量元素的绝对值之和
torch,abs(u).sum()

(<module 'torch' from '/opt/anaconda3/envs/learn/lib/python3.9/site-packages/torch/__init__.py'>,
 tensor(7.))

In [37]:
# 对矩阵计算 Frobenius 范数
x = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0]])
result = torch.norm(x, p='fro')
print(result)  # 输出: 5.4772

tensor(5.4772)
